CREATE TABLE home_db.property (
  `Property_ID` SMALLINT,
  `Property_Title` VARCHAR(64),
  `Address` VARCHAR(64),
  `Market` VARCHAR(7),
  `Flood` VARCHAR(13),
  `Street_Address` VARCHAR(36),
  `City` VARCHAR(23),
  `State` VARCHAR(2),
  `Zip` INT,
  `Property_Type` VARCHAR(18),
  `Highway` VARCHAR(4),
  `Train` VARCHAR(4),
  `Tax_Rate` FLOAT,
  `SQFT_Basement` SMALLINT,
  `HTW` VARCHAR(3),
  `Pool` VARCHAR(3),
  `Commercial` VARCHAR(3),
  `Water` VARCHAR(4),
  `Sewage` VARCHAR(6),
  `Year_Built` SMALLINT,
  `SQFT_MU` SMALLINT,
  `SQFT_Total` SMALLINT,
  `Parking` VARCHAR(8),
  `Bed` TINYINT,
  `Bath` TINYINT,
  `BasementYesNo` VARCHAR(3),
  `Layout` VARCHAR(8),
  `Rent_Restricted` VARCHAR(3),
  `Neighborhood_Rating` TINYINT,
  `Latitude` FLOAT,
  `Longitude` FLOAT,
  `Subdivision` VARCHAR(10),
  `School_Average` FLOAT,
  PRIMARY KEY (`Property_ID`)
);